artifact_location: file:///C:/Users/camil/OneDrive/Escritorio/Tesis/proyectos/main/services/mlflow/artifacts/580155929219684999
creation_time: 1748456933205
experiment_id: '580155929219684999'
last_update_time: 1748456933205
lifecycle_stage: active
name: Detección de fraude electrónico
