{
 "title": "Transacciones bancarias",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Transacciones procesadas (total)",
   "type": "stat",
   "description": "Cantidad total de registros recibidos por el sistema",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"total\" FROM transacciones LIMIT 50 "
    }
   ]
  },
  {
   "title": "Procesadas en el período seleccionado",
   "type": "stat",
   "description": "Muestra el número de transacciones detectadas en el período seleccionado",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS \"total\" \r\nFROM transacciones\r\nWHERE\r\n  $__timeFilter(Fecha) "
    }
   ]
  },
  {
   "title": "Evolucion de transacciones a lo largo del tiempo",
   "type": "barchart",
   "description": "Evolución de las transacciones procesadas, diferenciadas por clasificación.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp_procesado, '1s', 0) AS time,\r\n  COUNT(*) AS \"transacciones fraudulentas\"\r\nFROM transacciones\r\nWHERE $__timeFilter(timestamp_procesado) AND fraudindicator = 'fraudulento'\r\nGROUP BY time, FraudIndicator\r\nORDER BY time"
    },
    {
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp_procesado, '1s', 0) AS time,\r\n  COUNT(*) AS \"transacciones no fraudulentas\"\r\nFROM transacciones\r\nWHERE $__timeFilter(timestamp_procesado) AND fraudindicator = 'no fraudulento'\r\nGROUP BY time, FraudIndicator\r\nORDER BY time\r\n\r\n"
    }
   ]
  },
  {
   "title": "Distribución de predicciones del modelo",
   "type": "piechart",
   "description": "Comparación entre transacciones detectadas como fraudulentas y no fraudulentas.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fraudindicator as label,\r\n  COUNT(*) as \"transacciones no fraudulentas\"\r\nFROM transacciones\r\nWHERE fraudindicator = 'no fraudulento'\r\nGROUP BY FraudIndicator"
    },
    {
     "rawSql": "SELECT\r\n  FraudIndicator as label,\r\n  COUNT(*) as \"transacciones fraudulentas\"\r\nFROM transacciones\r\nWHERE fraudindicator = 'fraudulento'\r\nGROUP BY FraudIndicator"
    }
   ]
  },
  {
   "title": "Porcentaje de predicciones",
   "type": "piechart",
   "description": "Comparación entre transacciones detectadas como fraudulentas y no fraudulentas en el periodo seleccionado",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  fraudindicator as label,\r\n  COUNT(*) as \"transacciones no fraudulentas\"\r\nFROM transacciones\r\nWHERE fraudindicator = 'no fraudulento' AND $__timeFilter(Fecha)\r\nGROUP BY FraudIndicator"
    },
    {
     "rawSql": "SELECT\r\n  FraudIndicator as label,\r\n  COUNT(*) as \"transacciones fraudulentas\"\r\nFROM transacciones\r\nWHERE fraudindicator = 'fraudulento' AND $__timeFilter(Fecha)\r\nGROUP BY FraudIndicator"
    }
   ]
  },
  {
   "title": "Detalle de transacciones",
   "type": "table",
   "description": "Listado con información detallada de cada transacción procesada.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  usuario_id AS \"Usuario\",\r\n  transaccion_id AS \"ID de transacción\",\r\n  fraudindicator AS \"Indicador de fraude\",\r\n  category AS \"Categoría\",\r\n  transactionamount AS \"Monto de transacción\",\r\n  anomalyscore AS \"Puntaje de anomalía\",\r\n  accountbalance AS \"Saldo en cuenta\",\r\n  suspiciousflag AS \"Actividad sospechosa\",\r\n  fecha AS \"Fecha\"\r\nFROM transacciones\r\nWHERE\r\n  $__timeFilter(Fecha)\r\nORDER BY\r\n  Fecha DESC"
    }
   ]
  }
 ]
}