aliases: []
creation_timestamp: 1750555643523
current_stage: None
description: null
last_updated_timestamp: 1750555643523
name: XGBoostModel
run_id: 34305a75ccb04c19b699b5ae3c178635
run_link: null
source: file:///C:/Users/camil/OneDrive/Escritorio/Tesis/proyectos/main/services/mlflow/artifacts/580155929219684999/34305a75ccb04c19b699b5ae3c178635/artifacts/XGBoost_model
status: READY
status_message: null
storage_location: file:///C:/Users/camil/OneDrive/Escritorio/Tesis/proyectos/main/services/mlflow/artifacts/580155929219684999/34305a75ccb04c19b699b5ae3c178635/artifacts/XGBoost_model
user_id: null
version: 1
